apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookieflaskv2
spec:
  selector:
    matchLabels:
      run: cookieflaskv2
  replicas: 3
  template:
    metadata:
      labels:
        run: cookieflaskv2
    spec:
      containers:
      - name: dockercookieflaskv2
        image: docker-registry.infra.cloudera.com/e2einterop/docker_cookieflaskv2:latest
        ports:
        - containerPort: 5001
        - containerPort: 5002
