apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: milkbikisv2
spec:
  rules:
  - http:
      paths:
      - path: /fetch
        pathType: Prefix
        backend:
          service:
            name: cookieflaskservicev2
            port:
              number: 5001
      - path: /fetch/UI
        pathType: Prefix
        backend:
          service:
            name: cookieflaskservicev2
            port:
              number: 5002
