apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: milkbikisv2
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: cookieflaskservicev2
          servicePort: 5001
      - path: /UI
        backend:
          serviceName: cookieflaskservicev2
          servicePort: 5002
