apiVersion: v1
kind: Service
metadata:
  name: cookieflaskservice
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    run: cookieflask
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    run: cookieflask
