apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookieflask
spec:
  selector:
    matchLabels:
      run: cookieflask
  replicas: 1
  template:
    metadata:
      labels:
        run: cookieflask
    spec:
      containers:
      - name: dockercookieflask
        image: docker_cookieflask:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
