apiVersion: v1
kind: Service
metadata:
  name: cookieflaskservice
  labels:
    run: cookieflask
spec:
  type: NodePort
  ports:
  - port: 5001
    nodePort: 31444
    targetPort: 5001
    protocol: TCP
    name: http
  selector:
    run: cookieflask
